language: java

jdk:
  - openjdk16

env:
  global:
    - CODECOV_TOKEN="a29596cb-8eef-47e2-b9d5-12cb34332814"

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always
