version: '3.7'

services:
  db:
    image: docker.io/postgres
    restart: "no"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: tracker
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password

  adminer:
    image: docker.io/adminer
    restart: "no"
    ports:
      - "8081:8080"
